USE QL_BANHANG_TRANHCHAP
GO
ALTER PROC sp_CapNhat_DH_CN
@TRANGTHAIDH CHAR(20),
@MACN VARCHAR(10),
@MADH VARCHAR(10)
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT MADH FROM DON_DH WHERE MADH=@MADH )
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI DON HANG',16,1)
			RETURN
	END
	IF NOT EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
			RETURN
	END
	IF (@TRANGTHAIDH='PROCESSING' OR @TRANGTHAIDH='CANCELED' )
	BEGIN
		IF NOT EXISTS(SELECT MADH FROM DON_DH WHERE MADH=@MADH AND MACN=@MACN AND TRANGTHAIDH='AVAILABLE')
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG NHAN DON DUOC',16,1)
			RETURN
		END
		WAITFOR DELAY '0:00:10'
		UPDATE DON_DH SET TRANGTHAIDH=@TRANGTHAIDH WHERE MADH=@MADH --AND MACN=@MACN AND TRANGTHAIDH='AVAILABLE'
		IF @@ERROR <>0
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG NHAN DON DUOC',16,1)
			RETURN
		END
		IF @TRANGTHAIDH='CANCELED'
		BEGIN
		DECLARE @MAKH VARCHAR(10) = (SELECT MAKH FROM DON_DH WHERE MADH=@MADH)
		DECLARE @TONGTIEN INT = (SELECT PHIVANCHUYEN+ PHISP FROM DON_DH WHERE MADH=@MADH)
		UPDATE KHACHHANG SET SODUVI=SODUVI+@TONGTIEN WHERE MAKH=@MAKH
		IF @@ERROR <>0
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('LOI HE THONG THANH TOAN',16,1)
			RETURN
		END
		END
		COMMIT TRAN
		RETURN
	END


	RAISERROR ('TINH TRANG KHONG PHU HOP',16,1)
	ROLLBACK TRAN

	
GO
ALTER PROC sp_CapNhat_DH_KH
@TRANGTHAIDH CHAR(20),
@MAKH VARCHAR(10),
@MADH VARCHAR(10)
AS
BEGIN TRAN
	IF NOT EXISTS(SELECT MADH FROM DON_DH WHERE MADH=@MADH)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI DON HANG',16,1)
			RETURN
	END
	IF NOT EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH=@MAKH)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI KHACH HANG',16,1)
			RETURN
	END
	IF (@TRANGTHAIDH='CANCELED')
	BEGIN
		IF NOT EXISTS (SELECT MADH FROM DON_DH WHERE MADH=@MADH AND MAKH=@MAKH AND TRANGTHAIDH='AVAILABLE')
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG HUY DON DUOC',16,1)
			RETURN
		END
		UPDATE DON_DH SET TRANGTHAIDH=@TRANGTHAIDH WHERE MADH=@MADH-- AND MAKH=@MAKH AND TRANGTHAIDH='AVAILABLE'
		IF @@ERROR <>0
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG HUY DON DUOC',16,1)
			RETURN
		END
		DECLARE @TONGTIEN INT = (SELECT PHIVANCHUYEN+ PHISP FROM DON_DH WHERE MADH=@MADH)
		UPDATE KHACHHANG SET SODUVI=SODUVI+@TONGTIEN WHERE MAKH=@MAKH
		IF @@ERROR <>0
		BEGIN
			ROLLBACK TRAN
			RAISERROR ('LOI HE THONG THANH TOAN',16,1)
			RETURN
		END
		COMMIT TRAN
		RETURN
	END


	RAISERROR ('TINH TRANG KHONG PHU HOP',16,1)
	ROLLBACK TRAN

	
GO