
--T1: Chi nhánh thêm món ăn vào cửa hàng
--cài trigger
CREATE TRIGGER i_THUCDON
ON THUCDON
for INSERT
AS

BEGIN
	IF EXISTS(SELECT I.TENMONAN FROM inserted I WHERE LEN(I.TENMONAN)>80)
	BEGIN
		RAISERROR (N'TÊN DÀI QUÁ 80 KÝ TỰ',16,1)
	END
END
GO

--thêm món ăn
CREATE PROC sp_ThemThucDon_Tranhchap
	@TENMONAN NVARCHAR(100),
	@MOTA NVARCHAR (80),
	@GIA INT,
	@TINHTRANG NCHAR(20),
	@HINHANHTD BIT,
	@DIACHIHINHANHTD VARCHAR(100),
	@MACN CHAR(10),
	@MALAT CHAR(10)

AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN 
	BEGIN TRY
	DECLARE @ERROR INT = 0

	IF EXISTS (SELECT * FROM THUCDON WHERE TENMONAN = @TENMONAN AND MaCN = @MaCN)
	BEGIN
		PRINT @TENMONAN +N' ĐÃ TỒN TẠI'
		ROLLBACK TRAN
		RETURN 0
	RETURN
	END

	DECLARE @MAMONAN INT= (SELECT B.IDMAX
							FROM PHAMVIBANG B
							WHERE B.TENPHAMVI= 'THUCDON')
	UPDATE PHAMVIBANG SET IDMAX = IDMAX + 1 WHERE TENPHAMVI = 'THUCDON'

	INSERT INTO THUCDON
	VALUES (@MAMONAN, @TENMONAN, @MOTA, @GIA, @TINHTRANG, @HINHANHTD, @DIACHIHINHANHTD, @MACN, @MALAT)
	IF @@ERROR<>0
		SET @ERROR=@ERROR+1
	WAITFOR DELAY '00:00:10'
	END TRY

	BEGIN CATCH
	IF (@ERROR<>0)
	BEGIN
		PRINT N'KHÔNG THỂ THÊM MÓN ĂN'
		ROLLBACK TRAN
		RETURN 0
	END
	END CATCH
COMMIT TRAN
RETURN 1
GO

--T2: Khách hàng xem danh sách món ăn của cửa hàng
CREATE PROC sp_MonAn_ChiNhanh_Tranhchap @MACN CHAR(10)
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN

	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
		SELECT * FROM THUCDON WHERE MACN=@MACN
	ELSE
		RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
COMMIT TRAN
RETURN


