
--T1: Chi nhánh thêm món ăn vào cửa hàng
--cài trigger
CREATE TRIGGER i_THUCDON
ON THUCDON
for INSERT
AS

BEGIN
	IF EXISTS(SELECT I.TENMONAN FROM inserted I WHERE LEN(I.TENMONAN)>80)
	BEGIN
		RAISERROR (N'TÊN DÀI QUÁ 80 KÝ TỰ',16,1)
	END
END
GO

--thêm món ăn
CREATE PROC sp_ThemThucDon_Tranhchap
	@TENMONAN NVARCHAR(100),
	@MOTA NVARCHAR (80),
	@GIA INT,
	@HINHANHTD BIT,
	@DIACHIHINHANHTD VARCHAR(300),
	@MACN CHAR(10),
	@MALAT CHAR(10)

AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN 
	DECLARE @ERROR INT = 0

	IF NOT EXISTS(SELECT MACN  FROM CHINHANH WHERE MACN=@MACN)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
			RETURN
	END
	IF NOT EXISTS(SELECT MALAT  FROM LOAIAMTHUC WHERE MALAT=@MALAT)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('KHONG TON TAI LOAI AM THUC NAY',16,1)
			RETURN
	END
	IF EXISTS (SELECT MAMONAN FROM THUCDON WHERE  MACN=@MACN AND TENMONAN=@TENMONAN)
	BEGIN
			ROLLBACK TRAN
			RAISERROR ('DA TON TAI MON AN NAY',16,1)
			RETURN
	END
	DECLARE @MAMONAN CHAR(10)
	EXEC sp_IDMAX 'THUCDON',@MAMONAN OUT

	INSERT INTO THUCDON
	VALUES (@MAMONAN, @TENMONAN, @MOTA, @GIA, 'AVAILABLE', @HINHANHTD, @DIACHIHINHANHTD, @MACN, @MALAT)
	IF @@ERROR<>0
		SET @ERROR=@ERROR+1
	WAITFOR DELAY '00:00:10'

	IF (@ERROR<>0)
	BEGIN
		PRINT N'KHÔNG THỂ THÊM MÓN ĂN'
		ROLLBACK TRAN
		RETURN 0
	END
COMMIT TRAN
RETURN 1
GO

--T2: Khách hàng xem danh sách món ăn của cửa hàng
CREATE PROC sp_MonAn_ChiNhanh_Tranhchap @MACN CHAR(10)
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN

	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
		SELECT * FROM THUCDON WHERE MACN=@MACN
	ELSE
		RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
COMMIT TRAN
RETURN


