--Partition Tai khoan--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP LOAITK0_3
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP LOAITK4
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP LOAITK5 
GO

SELECT name AS AvailableFilegroups
FROM sys.filegroups
WHERE type = 'FG'

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part0_3],
    FILENAME = 'D:\LOAITK0_3.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [LOAITK0_3]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part4],
    FILENAME = 'D:\LOAITK4.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [LOAITK4]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part5],
    FILENAME = 'D:\LOAITK5.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [LOAITK5]


--Partition khach hang--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTG_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTG_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTG_2023
GO

SELECT name AS AvailableFilegroups
FROM sys.filegroups
WHERE type = 'FG'

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part2021],
    FILENAME = 'D:\NGAYTG_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTG_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part2022],
    FILENAME = 'D:\NGAYTG_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTG_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [Part2023],
    FILENAME = 'D:\NGAYTG_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTG_2023]


--Partition tai xe--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTXTG_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTXTG_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYTXTG_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNGAYTXTG2021],
    FILENAME = 'D:\NGAYTXTG_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTXTG_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNGAYTXTG2022],
    FILENAME = 'D:\NGAYTXTG_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTXTG_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNGAYTXTG2023],
    FILENAME = 'D:\NGAYTXTG_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYTXTG_2023]


--Partition thong tin hop dong--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP TGHH_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP TGHH_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP TGHH_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartTGHH2021],
    FILENAME = 'D:\TGHH_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [TGHH_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartTGHH2022],
    FILENAME = 'D:\TGHH_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [TGHH_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartTGHH2023],
    FILENAME = 'D:\TGHH_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [TGHH_2023]

--Partition don dat hang--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPDON_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPDON_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPDON_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLD2021],
    FILENAME = 'D:\NGAYLAPDON_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPDON_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLD2022],
    FILENAME = 'D:\NGAYLAPDON_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPDON_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLD2023],
    FILENAME = 'D:\NGAYLAPDON_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPDON_2023]

--Partition thuc don dat hang--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPTHUCDON_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPTHUCDON_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NGAYLAPTHUCDON_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLTD2021],
    FILENAME = 'D:\NGAYLAPTHUCDON_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPTHUCDON_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLTD2022],
    FILENAME = 'D:\NGAYLAPTHUCDON_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPTHUCDON_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLTD2023],
    FILENAME = 'D:\NGAYLAPTHUCDON_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NGAYLAPTHUCDON_2023]

--Partition danh gia chi nhanh--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGCN_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGCN_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGCN_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGCN2021],
    FILENAME = 'D:\NLDGCN_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGCN_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGCN2022],
    FILENAME = 'D:\NLDGCN_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGCN_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGCN2023],
    FILENAME = 'D:\NLDGCN_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGCN_2023]

--Partition danh gia mon an--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGMA_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGMA_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGMA_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGMA2021],
    FILENAME = 'D:\NLDGMA_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGMA_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGMA2022],
    FILENAME = 'D:\NLDGMA_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGMA_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGMA2023],
    FILENAME = 'D:\NLDGMA_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGMA_2023]

--Partition danh gia tai xe--
ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGTX_2021
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGTX_2022
GO

ALTER DATABASE QL_BANHANG
ADD FILEGROUP NLDGTX_2023
GO

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGTX2021],
    FILENAME = 'D:\NLDGTX_2021.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGTX_2021]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGTX2022],
    FILENAME = 'D:\NLDGTX_2022.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGTX_2022]

ALTER DATABASE [QL_BANHANG]
    ADD FILE 
    (
    NAME = [PartNLDGTX2023],
    FILENAME = 'D:\NLDGTX_2023.ndf',
        SIZE = 3072 KB, 
        MAXSIZE = UNLIMITED, 
        FILEGROWTH = 1024 KB
    ) TO FILEGROUP [NLDGTX_2023]
--PARTITION
USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DGCN](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_DGCN] AS PARTITION [PART_F_DGCN] TO ([NLDGCN_2021], [NLDGCN_2022], [NLDGCN_2023], [PRIMARY])






ALTER TABLE [dbo].[DANHGIA_CHINHANH] DROP CONSTRAINT [PK_DANHGIA_CHINHANH] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DANHGIA_CHINHANH] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DGCN_638073183461933639] ON [dbo].[DANHGIA_CHINHANH]
(
	[NGAYLAP] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DGCN]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DGCN_638073183461933639] ON [dbo].[DANHGIA_CHINHANH]








COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DGMA](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_DGMA] AS PARTITION [PART_F_DGMA] TO ([NLDGMA_2021], [NLDGMA_2022], [NLDGMA_2023], [PRIMARY])






ALTER TABLE [dbo].[DANHGIA_MONAN] DROP CONSTRAINT [PK_DANHGIA_MONAN] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DANHGIA_MONAN] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC,
	[MAMONAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DGMA_638073185050397937] ON [dbo].[DANHGIA_MONAN]
(
	[NGAYLAP] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DGMA]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DGMA_638073185050397937] ON [dbo].[DANHGIA_MONAN]








COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DGTX](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_DGTX] AS PARTITION [PART_F_DGTX] TO ([NLDGTX_2021], [NLDGTX_2022], [NLDGTX_2023], [PRIMARY])






ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [PK_DANHGIA_TX] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DANHGIA_TX] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DGTX_638073186971305613] ON [dbo].[DANHGIA_TX]
(
	[NGAYLAP] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DGTX]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DGTX_638073186971305613] ON [dbo].[DANHGIA_TX]








COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_DH](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_DH] AS PARTITION [PART_F_DH] TO ([NGAYLAPDON_2021], [NGAYLAPDON_2022], [NGAYLAPDON_2023], [PRIMARY])


ALTER TABLE [dbo].[DANHGIA_CHINHANH] DROP CONSTRAINT [FK_DG_DH]


ALTER TABLE [dbo].[DANHGIA_MONAN] DROP CONSTRAINT [FK_DGMA_DH]


ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [FK_DGTX_DH]


ALTER TABLE [dbo].[THUCDONDATHANG] DROP CONSTRAINT [FK_TDDH_DH]


ALTER TABLE [dbo].[TUYCHONMONDATHANG] DROP CONSTRAINT [FK_TCMDH_DH]






ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [PK_DON_DH] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[DON_DH] ADD PRIMARY KEY NONCLUSTERED 
(
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_DH_638073175574493854] ON [dbo].[DON_DH]
(
	[NGAYLAP] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_DH]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_DH_638073175574493854] ON [dbo].[DON_DH]




ALTER TABLE [dbo].[DANHGIA_CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_DG_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_CHINHANH] CHECK CONSTRAINT [FK_DG_DH]


ALTER TABLE [dbo].[DANHGIA_MONAN]  WITH CHECK ADD  CONSTRAINT [FK_DGMA_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_MONAN] CHECK CONSTRAINT [FK_DGMA_DH]


ALTER TABLE [dbo].[DANHGIA_TX]  WITH CHECK ADD  CONSTRAINT [FK_DGTX_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[DANHGIA_TX] CHECK CONSTRAINT [FK_DGTX_DH]


ALTER TABLE [dbo].[THUCDONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_TDDH_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[THUCDONDATHANG] CHECK CONSTRAINT [FK_TDDH_DH]


ALTER TABLE [dbo].[TUYCHONMONDATHANG]  WITH CHECK ADD  CONSTRAINT [FK_TCMDH_DH] FOREIGN KEY([MADH])
REFERENCES [dbo].[DON_DH] ([MADH])
ALTER TABLE [dbo].[TUYCHONMONDATHANG] CHECK CONSTRAINT [FK_TCMDH_DH]






COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_KH](datetime) AS RANGE RIGHT FOR VALUES (N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_KH] AS PARTITION [PART_F_KH] TO ([NGAYTG_2021], [NGAYTG_2022], [NGAYTG_2023], [PRIMARY])


ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [FK_DH_KH]






ALTER TABLE [dbo].[KHACHHANG] DROP CONSTRAINT [PK_KHACHHANG] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[KHACHHANG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_KH_638073064601035851] ON [dbo].[KHACHHANG]
(
	[NGAYTG] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_KH]([NGAYTG])


DROP INDEX [ClusteredIndex_on_PART_S_KH_638073064601035851] ON [dbo].[KHACHHANG]




ALTER TABLE [dbo].[DON_DH]  WITH CHECK ADD  CONSTRAINT [FK_DH_KH] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ALTER TABLE [dbo].[DON_DH] CHECK CONSTRAINT [FK_DH_KH]






COMMIT TRANSACTION
USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TDDH](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_TDDH] AS PARTITION [PART_F_TDDH] TO ([NGAYLAPTHUCDON_2021], [NGAYLAPTHUCDON_2022], [NGAYLAPTHUCDON_2023], [PRIMARY])






ALTER TABLE [dbo].[THUCDONDATHANG] DROP CONSTRAINT [PK_THUCDONDATHANG] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[THUCDONDATHANG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAMONAN] ASC,
	[MADH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TDDH_638073179621251855] ON [dbo].[THUCDONDATHANG]
(
	[NGAYLAP] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TDDH]([NGAYLAP])


DROP INDEX [ClusteredIndex_on_PART_S_TDDH_638073179621251855] ON [dbo].[THUCDONDATHANG]








COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TK](int) AS RANGE LEFT FOR VALUES (N'3', N'4', N'5')


CREATE PARTITION SCHEME [PART_S_TK] AS PARTITION [PART_F_TK] TO ([LOAITK0_3], [LOAITK4], [LOAITK5], [PRIMARY])


ALTER TABLE [dbo].[CHINHANH] DROP CONSTRAINT [FK_CN_TK]


ALTER TABLE [dbo].[DOITAC] DROP CONSTRAINT [FK_DT_TK]


ALTER TABLE [dbo].[KHACHHANG] DROP CONSTRAINT [FK_KH_TK]


ALTER TABLE [dbo].[NHANVIEN] DROP CONSTRAINT [FK_NV_TK]


ALTER TABLE [dbo].[QUANTRIVIEN] DROP CONSTRAINT [FK_QTV_TK]


ALTER TABLE [dbo].[QUYENTHAOTAC] DROP CONSTRAINT [FK_QTT_TK]


ALTER TABLE [dbo].[TAIXE] DROP CONSTRAINT [FK_TX_TK]






ALTER TABLE [dbo].[TAIKHOAN] DROP CONSTRAINT [PK_TAIKHOAN] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[TAIKHOAN] ADD PRIMARY KEY NONCLUSTERED 
(
	[MATK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TK_638073027221677830] ON [dbo].[TAIKHOAN]
(
	[LOAITK]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TK]([LOAITK])


DROP INDEX [ClusteredIndex_on_PART_S_TK_638073027221677830] ON [dbo].[TAIKHOAN]




ALTER TABLE [dbo].[CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_CN_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[CHINHANH] CHECK CONSTRAINT [FK_CN_TK]


ALTER TABLE [dbo].[DOITAC]  WITH CHECK ADD  CONSTRAINT [FK_DT_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[DOITAC] CHECK CONSTRAINT [FK_DT_TK]


ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KH_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KH_TK]


ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NV_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NV_TK]


ALTER TABLE [dbo].[QUANTRIVIEN]  WITH CHECK ADD  CONSTRAINT [FK_QTV_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[QUANTRIVIEN] CHECK CONSTRAINT [FK_QTV_TK]


ALTER TABLE [dbo].[QUYENTHAOTAC]  WITH CHECK ADD  CONSTRAINT [FK_QTT_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[QUYENTHAOTAC] CHECK CONSTRAINT [FK_QTT_TK]


ALTER TABLE [dbo].[TAIXE]  WITH CHECK ADD  CONSTRAINT [FK_TX_TK] FOREIGN KEY([MATK])
REFERENCES [dbo].[TAIKHOAN] ([MATK])
ALTER TABLE [dbo].[TAIXE] CHECK CONSTRAINT [FK_TX_TK]






COMMIT TRANSACTION

USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TTHD](date) AS RANGE RIGHT FOR VALUES (N'2022-01-01', N'2023-01-01', N'2024-01-01')


CREATE PARTITION SCHEME [PART_S_TTHD] AS PARTITION [PART_F_TTHD] TO ([TGHH_2021], [TGHH_2022], [TGHH_2023], [PRIMARY])






ALTER TABLE [dbo].[THONGTIN_HOPDONG] DROP CONSTRAINT [PK_THONGTIN_HOPDONG] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[THONGTIN_HOPDONG] ADD PRIMARY KEY NONCLUSTERED 
(
	[MAHD] ASC,
	[STT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TTHD_638073166823412133] ON [dbo].[THONGTIN_HOPDONG]
(
	[TGHH] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TTHD]([TGHH])


DROP INDEX [ClusteredIndex_on_PART_S_TTHD_638073166823412133] ON [dbo].[THONGTIN_HOPDONG]








COMMIT TRANSACTION


USE [QL_BANHANG]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [PART_F_TX](datetime) AS RANGE RIGHT FOR VALUES (N'2021-01-01T00:00:00', N'2022-01-01T00:00:00', N'2023-01-01T00:00:00', N'2024-01-01T00:00:00')


CREATE PARTITION SCHEME [PART_S_TX] AS PARTITION [PART_F_TX] TO ([PRIMARY], [NGAYTXTG_2021], [NGAYTXTG_2022], [NGAYTXTG_2023], [PRIMARY])


ALTER TABLE [dbo].[DANHGIA_TX] DROP CONSTRAINT [FK_DG_TX]


ALTER TABLE [dbo].[DON_DH] DROP CONSTRAINT [FK_DH_TX]


ALTER TABLE [dbo].[TAIXE_CHITIET] DROP CONSTRAINT [FK_TX_CT]






ALTER TABLE [dbo].[TAIXE] DROP CONSTRAINT [PK_TAIXE] WITH ( ONLINE = OFF )


SET ANSI_PADDING ON

ALTER TABLE [dbo].[TAIXE] ADD PRIMARY KEY NONCLUSTERED 
(
	[MATX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PART_S_TX_638073155255713363] ON [dbo].[TAIXE]
(
	[NGAYTG] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PART_S_TX]([NGAYTG])


DROP INDEX [ClusteredIndex_on_PART_S_TX_638073155255713363] ON [dbo].[TAIXE]




ALTER TABLE [dbo].[DANHGIA_TX]  WITH CHECK ADD  CONSTRAINT [FK_DG_TX] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[DANHGIA_TX] CHECK CONSTRAINT [FK_DG_TX]


ALTER TABLE [dbo].[DON_DH]  WITH CHECK ADD  CONSTRAINT [FK_DH_TX] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[DON_DH] CHECK CONSTRAINT [FK_DH_TX]


ALTER TABLE [dbo].[TAIXE_CHITIET]  WITH CHECK ADD  CONSTRAINT [FK_TX_CT] FOREIGN KEY([MATX])
REFERENCES [dbo].[TAIXE] ([MATX])
ALTER TABLE [dbo].[TAIXE_CHITIET] CHECK CONSTRAINT [FK_TX_CT]






COMMIT TRANSACTION


