--INDEX TAI KHOAN--

CREATE INDEX idx_DANGNHAP ON TAIKHOAN (TENTK, MATKHAUTK,TINHTRANGTK) INCLUDE (MATK,NGAYTG)

--INDEX KHACH HANG--
CREATE INDEX idx_MATK ON KHACHHANG (NGAYTG,MATK) INCLUDE (MAKH)

--INDEX TAI XE
CREATE INDEX idx_MADIACHI ON TAIXE_CHITIET (MADIACHI)
CREATE INDEX idx_MATK ON TAIXE (NGAYTG,MATK) INCLUDE (MATX)
CREATE INDEX idx_MATKNGANHANG ON TAIXE_CHITIET (MATKNGANHANG)
--INDEX DOI TAC--
CREATE INDEX idx_MATK ON DOITAC (MATK) INCLUDE (MADOITAC)
CREATE INDEX idx_MATKNGANHANG ON DOITAC_CHITIET (MATKNGANHANG)
CREATE INDEX idx_MADIACHI ON DOITAC_CHITIET (MADIACHI)
--INDEX CHI NHANH--
CREATE INDEX idx_MATK ON CHINHANH (MATK) INCLUDE (MACN)
CREATE INDEX idx_MATKNGANHANG ON CHINHANH (MATKNGANHANG)
CREATE INDEX idx_MADT ON CHINHANH (MADT)
--INDEX CUA HANG--
CREATE INDEX idx_TENCH ON CUAHANG (TENCH)
CREATE INDEX idx_SLDH ON CUAHANG (SLDH)
--INDEX THUC DON--
CREATE INDEX idx_TENMONAN ON THUCDON (TENMONAN)
CREATE INDEX idx_GIA ON THUCDON (GIA)
CREATE INDEX idx_SLDH ON THUCDON (SLDH)
CREATE INDEX idx_MACN ON THUCDON (MACN)
--INDEX NHAN VIEN--
CREATE INDEX idx_MATK ON NHANVIEN (MATK) INCLUDE (MANHANVIEN)
CREATE INDEX idx_MATKNGANHANG ON NHANVIEN_CHITIET (MATKNGANHANG)
CREATE INDEX idx_MADIACHI ON NHANVIEN_CHITIET (MADIACHI)
--INDEX QUAN TRI VIEN
CREATE INDEX idx_MATK ON QUANTRIVIEN (MATK) INCLUDE (MAQTV)
CREATE INDEX idx_MATKNGANHANG ON QUANTRIVIEN (MATKNGANHANG)
CREATE INDEX idx_MADIACHI ON QUANTRIVIEN (MADIACHI)
--INDEX HOP DONG--
CREATE INDEX idx_MADT ON HOPDONG (MADOITAC)
--INDEX THONG TIN HOP DONG--
CREATE INDEX idx_MANV ON THONGTIN_HOPDONG (MANHANVIEN)
--INDEX HOPDONG CHI NHANH

CREATE INDEX idx_HD_HD ON HOPDONGCHINHANH (MAHD)
--INDEX DON DAT HANG--
CREATE INDEX idx_MAKH ON DON_DH (MAKH) INCLUDE (PHIVANCHUYEN,PHISP)
CREATE INDEX idx_MACN ON DON_DH (MACN) INCLUDE (PHISP,PTHH)
CREATE INDEX idx_MADT ON DON_DH (MADT) INCLUDE (PHISP,PTHH)
CREATE INDEX idx_MATX ON DON_DH (MATX) INCLUDE (PHIVANCHUYEN)
CREATE INDEX idx_TDDH ON THUCDONDATHANG (MADH) INCLUDE (MAMONAN)
CREATE INDEX idx_TDDHMA ON THUCDONDATHANG (MAMONAN) INCLUDE (SOLUONG,GIABAN)

--INDEX DANH GIA CHI NHANH--
CREATE INDEX idx_MACN ON DANHGIA_CHINHANH (MACN)
CREATE INDEX idx_MADT ON DANHGIA_CHINHANH (MADT)
--INDEX DANH GIA MON AN--
CREATE INDEX idx_MAMONAN ON DANHGIA_MONAN (MAMONAN)
--INDEX DANH GIA TAI XE--
CREATE INDEX idx_MATX ON DANHGIA_TX (MATX)
--INDEX PHUONG--
CREATE INDEX idx_MAHUYEN ON PHUONG (MAHUYEN)
--INDEX DIA CHI--
CREATE INDEX idx_MAPHUONG ON DIACHI (MAPHUONG)
