USE QL_BANHANG_TRANHCHAP
GO
CREATE ALTER TRIGGER i_TAIKHOAN
ON TAIKHOAN
for INSERT
AS
BEGIN
	DECLARE @TENTK VARCHAR(50),@MATK CHAR(10)

	SELECT @TENTK=I.TENTK,@MATK=I.MATK FROM inserted I
	IF EXISTS(SELECT * FROM TAIKHOAN WHERE TENTK=@TENTK AND MATK<>@MATK)
	BEGIN
		RAISERROR ('TAI KHOAN DA TON TAI',16,1)
	END
END
GO
ALTER PROC sp_ThemTaiKhoan
	@MATK CHAR(10), 
	@TENTK VARCHAR(50),
	@TINHTRANGTK NVARCHAR(30),
	@MATKHAUTK VARCHAR(50),
	@LOAITK INT
AS
BEGIN TRAN
	

	INSERT INTO TAIKHOAN
	VALUES
		(@MATK, @TENTK, @TINHTRANGTK, @MATKHAUTK, @LOAITK)
	WAITFOR DELAY '0:00:10'
	IF @@ERROR<>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG KHÔNG TẠO TÀI KHOẢN ĐƯỢC'
		ROLLBACK TRAN
		RETURN 
	END 
COMMIT TRAN
return 
GO

GO
CREATE 
PROC sp_DANGKYKH_TRANHCHAP
	@TENTK VARCHAR(50),
	@MATKHAUTK VARCHAR(50)
AS
BEGIN TRAN
DECLARE @IDTK int 
EXEC sp_IDMAX 'TAIKHOAN',@IDTK OUT
EXEC sp_ThemTaiKhoan @IDTK,@TENTK,'AVAILABLE',@MATKHAUTK,5
IF @@ERROR <>0
	BEGIN 
		RAISERROR (N'LỖI HỆ THỐNG KHÔNG TẠO TÀI KHOẢN ĐƯỢC',16,1)
		ROLLBACK 
		RETURN 
	END 
DECLARE @IDKH int 
EXEC sp_IDMAX 'KHACHHANG',@IDKH OUT
EXEC sp_ThemKhachHang @IDKH,@TENTK,NULL,NULL,0,NULL,NULL,@IDTK,NULL,0
IF @@ERROR <>0
	BEGIN 
		PRINT N'LỖI HỆ THỐNG KHÔNG TẠO TÀI KHOẢN ĐƯỢC'
		ROLLBACK 
		RETURN 
	END 
COMMIT 
GO
-- Đăng nhập
CREATE 
--ALTER
PROC sp_DANGNHAP_TRANHCHAP
	@LOAITK INT,
	@TENTK NVARCHAR(50),
	@MATKHAUTK NVARCHAR(50)

AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
IF @LOAITK<0 OR @LOAITK>5
	BEGIN
		RAISERROR (N'KHÔNG TỒN TẠI NGƯỜI DÙNG',16,1);
		ROLLBACK
		RETURN
	END
IF NOT EXISTS( SELECT TENTK FROM TAIKHOAN WHERE LOAITK=@LOAITK AND TENTK=@TENTK AND @MATKHAUTK=MATKHAUTK AND TINHTRANGTK='AVAILABLE')
BEGIN
		RAISERROR (N'TEN TK HOAC MATKHAU DANG NHAP KHONG DUNG',16,1);
		ROLLBACK
		RETURN
END
IF @LOAITK=0
	BEGIN
		SELECT QTV.MAQTV FROM QUANTRIVIEN QTV JOIN TAIKHOAN TK ON QTV.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
	END
IF @LOAITK=1
BEGIN
		SELECT NV.MANHANVIEN FROM NHANVIEN NV JOIN TAIKHOAN TK ON NV.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
END

IF @LOAITK=2
BEGIN
		SELECT DT.MADOITAC FROM DOITAC DT JOIN TAIKHOAN TK ON DT.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
END
IF @LOAITK=3
BEGIN
		SELECT CN.MACN FROM CHINHANH CN JOIN TAIKHOAN TK ON CN.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
END
IF @LOAITK=4
BEGIN
		SELECT TX.MATX FROM TAIXE TX JOIN TAIKHOAN TK ON TX.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
END

IF @LOAITK=5
BEGIN
		SELECT KH.MAKH FROM KHACHHANG KH JOIN TAIKHOAN TK ON KH.MATK=TK.MATK AND TK.TENTK=@TENTK AND TK.MATKHAUTK=@MATKHAUTK
		COMMIT TRAN
		RETURN
END
GO	