USE QL_BANHANG
GO 
CREATE INDEX idx_MAKH ON DON_DH (MAKH) INCLUDE (PHIVANCHUYEN,PHISP)
GO
DROP INDEX idx_MAKH ON DON_DH 
GO
ALTER PROC sp_DonHang_KH
@MAKH VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME
AS
	IF EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH=@MAKH)
	BEGIN
	SELECT TOP (100) * FROM DON_DH DH  JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH
	WHERE DH.MAKH=@MAKH
	END

GO
ALTER PROC sp_DonHang_KH
@MAKH VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME
AS

	SELECT TOP(50) * FROM DON_DH DH 
	WHERE   MAKH=@MAKH

GO
DECLARE @MAKH VARCHAR(10)='5'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='1'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='1000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='10000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='20000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='25000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='30000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='35000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='40000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='50000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='60000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='70000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='80000'
UPDATE DON_DH SET MAKH =@MAKH WHERE MADH='90000'