USE QL_BANHANG
GO 


ALTER PROC sp_MonAn_TheoGia
@SL int,
@THUTU VARCHAR(10)
AS
	if @THUTU='INCREASE'
	BEGIN

	SELECT TOP (@SL) * FROM THUCDON ORDER BY GIA ASC
	SELECT COUNT(TD.MAMONAN) SOLUONG FROM ( SELECT TOP (@SL) * FROM THUCDON WHERE TINHTRANG != 'DELETED' ORDER BY GIA ASC) TD
	RETURN
	END
	IF @THUTU='DECREASE'
	BEGIN
	SELECT TOP (@SL) * FROM THUCDON ORDER BY GIA DESC
	SELECT COUNT(TD.MAMONAN) SOLUONG FROM ( SELECT TOP (@SL) * FROM THUCDON ORDER BY GIA DESC) TD
	RETURN
	END
GO
--Lấy món theo chi nhánh
ALTER PROC sp_MonAn_ChiNhanh
@SL int,
@MACN VARCHAR(10)
AS
	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
	
	SELECT TOP (@SL) * FROM THUCDON WHERE MACN=@MACN 
	ELSE
	RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
GO

ALTER PROC sp_MonAn_ChiNhanh_KhachHang
@SL int,
@MACN VARCHAR(10)
AS
	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
	BEGIN
	SELECT TOP (@SL) * FROM THUCDON WHERE MACN=@MACN  AND TINHTRANG='AVAILABLE'
	SELECT COUNT (TD.MAMONAN) FROM(	SELECT TOP (@SL) * FROM THUCDON WHERE MACN=@MACN  AND TINHTRANG='AVAILABLE') TD
	END
	ELSE
	RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
GO
--Lấy món theo loại ẩm thực

ALTER PROC sp_MonAn_LoaiAmThuc
@SL int,
@MALAT VARCHAR(10)
AS
	IF EXISTS(SELECT MALAT FROM LOAIAMTHUC WHERE MALAT=@MALAT)
	SELECT TOP (@SL) * FROM THUCDON WHERE MALAT=@MALAT
	ELSE
	RAISERROR ('KHONG TON TAI LOAI AM THUC',16,1)
GO
-- Lấy đơn hàng chi tiết
ALTER PROC sp_DonHang_ChiTiet
@MAKH VARCHAR(10),
@MADH VARCHAR(10),
@USER_TYPE VARCHAR(10)
AS
	BEGIN
	IF @USER_TYPE = '3'
		BEGIN
		IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MAKH)
		select tddh.MAMONAN, td.TENMONAN, td.GIA, tddh.SOLUONG from  DON_DH dh join THUCDONDATHANG tddh on dh.MADH = tddh.MADH join THUCDON td on td.MAMONAN = tddh.MAMONAN 	
		WHERE DH.MACN=@MAKH AND dh.MADH = @MADH
		END
	ELSE IF @USER_TYPE = '4'
		BEGIN
		IF EXISTS(SELECT MATX FROM TAIXE WHERE MATX=@MAKH)
		select tddh.MAMONAN, td.TENMONAN, td.GIA, tddh.SOLUONG from  DON_DH dh join THUCDONDATHANG tddh on dh.MADH = tddh.MADH join THUCDON td on td.MAMONAN = tddh.MAMONAN 	
		WHERE DH.MATX=@MAKH AND dh.MADH = @MADH
		END
	ELSE IF @USER_TYPE = '5'
		BEGIN
		IF EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH=@MAKH)
		select tddh.MAMONAN, td.TENMONAN, td.GIA, tddh.SOLUONG from  DON_DH dh join THUCDONDATHANG tddh on dh.MADH = tddh.MADH join THUCDON td on td.MAMONAN = tddh.MAMONAN 	
		WHERE DH.MAKH=@MAKH AND dh.MADH = @MADH
		END
	ELSE
	RAISERROR ('KHONG TON TAI KHACH HANG',16,1)
	END
GO
-- lấy đơn hàng khách hàng
SELECT
 a.name AS Index_Name,
 OBJECT_NAME(a.object_id),
 COL_NAME(b.object_id,b.column_id) AS Column_Name,
 b.index_column_id,
 b.key_ordinal,
 b.is_included_column
FROM
 sys.indexes AS a
INNER JOIN
 sys.index_columns AS b
       ON a.object_id = b.object_id AND a.index_id = b.index_id
WHERE
        a.is_hypothetical = 0 AND
 a.object_id = OBJECT_ID('DON_DH');
EXEC sp_DonHang_KH '5',null,null
UPDATE DON_DH SET MATX='100' WHERE CONVERT(INT,MADH) >99000
UPDATE DON_DH SET MAKH ='5' WHERE MADH='1'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='1000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='10000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='20000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='25000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='30000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='35000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='40000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='50000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='60000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='70000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='80000'
UPDATE DON_DH SET MAKH ='5' WHERE MADH='90000'
ALTER PROC sp_DonHang_KH
@MAKH VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME
AS
	IF EXISTS(SELECT MAKH FROM KHACHHANG WHERE MAKH=@MAKH)
	BEGIN
	SELECT TOP (100) * FROM DON_DH DH  JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH
	WHERE DH.MAKH=@MAKH
	END

GO
-- LẤY ĐƠN HÀNG TÀI XẾ
EXEC sp_DonHang_TX '5',null,null
UPDATE DON_DH SET MATX ='5' WHERE MADH='1'
UPDATE DON_DH SET MATX ='5' WHERE MADH='1000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='10000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='20000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='30000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='40000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='50000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='60000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='70000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='80000'
UPDATE DON_DH SET MATX ='5' WHERE MADH='90000'
ALTER PROC sp_DonHang_TX
@MATX VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME
AS
	IF EXISTS(SELECT MATX FROM TAIXE WHERE MATX=@MATX)
	BEGIN
	SELECT TOP (100) * FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN 
	WHERE DH.MATX=@MATX
	--order by cast(MADH as int) desc
	SELECT SUM(PHIVANCHUYEN) FROM DON_DH WHERE MATX=@MATX
	END

	ELSE
	RAISERROR ('KHONG TON TAI TAI XE',16,1)
GO
-- LẤY ĐƠN HÀNG CHƯA ĐƯỢC GIAO
ALTER PROC sp_DonHang_CanGiao
AS
	SELECT * FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN 
	WHERE DH.TRANGTHAIDH='PROCESSING' AND DH.MATX IS NULL AND DH.NGAYLAP> DATEADD(DAY,-1,GETDATE())
GO
-- LẤY ĐƠN HÀNG THEO TÌNH TRẠNG CỦA CHI NHÁNH
ALTER PROC sp_DonHang_CN_XuLy
@MACN VARCHAR(10),
@TRANGTHAIDH CHAR(20),
@TGBD DATETIME,
@TGKT DATETIME
AS
	SELECT * FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH LEFT JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN 
	WHERE  DH.MACN=@MACN AND DH.TRANGTHAIDH=@TRANGTHAIDH
	order by cast(MADH as int)
	SELECT COUNT (DON.MADH) FROM (	SELECT DH.MADH FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH LEFT JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN 
	WHERE  DH.MACN=@MACN AND DH.TRANGTHAIDH=@TRANGTHAIDH) DON
GO
-- LẤY ĐƠN HÀNG CHI NHANH
EXEC sp_DonHang_CN '1','2020'
ALTER PROC sp_DonHang_CN
@MACN VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME,
@TRANGTHAIDH CHAR(20)
AS
	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
	BEGIN
	IF @TRANGTHAIDH='ALL'
	BEGIN
	SELECT DH.MADH,DH.NGAYLAP,DH.TRANGTHAIDH,DH.HINHTHUCTT,DH.PHISP,DH.PHIVANCHUYEN,DH.MADCGH,DH.MAKH,DH.MACN,DH.MATX,DH.MAKHUVUC,KH.TEN TENKH,TX.TEN TENTX,TX.BIENSOXE FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH LEFT JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN  
	WHERE DH.NGAYLAP BETWEEN @TGBD AND @TGKT AND CN.MACN=@MACN 
	ORDER BY DH.NGAYLAP DESC
	SELECT COUNT(MADH)SOLUONG FROM DON_DH WHERE MACN=@MACN
	END
	ELSE
	BEGIN
	SELECT * FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH LEFT JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN 
	WHERE DH.NGAYLAP BETWEEN @TGBD AND @TGKT AND CN.MACN=@MACN  AND DH.TRANGTHAIDH=@TRANGTHAIDH
	ORDER BY DH.NGAYLAP DESC
	SELECT COUNT(MADH) SOLUONG,SUM(PHISP) DOANHTHU FROM DON_DH WHERE MACN=@MACN AND TRANGTHAIDH=@TRANGTHAIDH
	END
	END
	ELSE
	RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
GO

-- LẤY ĐƠN HÀNG DOI TAC
ALTER PROC sp_DonHang_DT
@MADT VARCHAR(10),
@TGBD DATETIME,
@TGKT DATETIME
AS
	IF EXISTS(SELECT MADOITAC FROM DOITAC WHERE MADOITAC=@MADT)
	SELECT * FROM DON_DH DH JOIN KHACHHANG KH ON DH.MAKH=KH.MAKH LEFT JOIN TAIXE TX ON DH.MATX=TX.MATX JOIN CHINHANH CN ON DH.MACN=CN.MACN JOIN CUAHANG CH ON CH.MACN=CN.MACN JOIN DOITAC DT ON DT.MADOITAC=CN.MADT
	WHERE DT.MADOITAC=@MADT
	ELSE
	RAISERROR ('KHONG TON TAI DOI TAC',16,1)
GO
ALTER PROC sp_Lay_CN
@MACN VARCHAR(10)
AS
	IF EXISTS(SELECT MACN FROM CHINHANH WHERE MACN=@MACN)
	BEGIN
	SELECT * FROM CHINHANH CN JOIN CUAHANG CH ON CH.MACN=CN.MACN
	WHERE CN.MACN=@MACN
	SELECT * FROM THUCDON WHERE MACN=@MACN
	END
	ELSE
	RAISERROR ('KHONG TON TAI CHI NHANH',16,1)
GO
-- Tạo thực đơn

GO

-- Lấy hợp đồng chưa xác nhận
ALTER PROC sp_LayHopDong_ChuaXacNhan
AS
	SELECT * FROM THONGTIN_HOPDONG TTHD JOIN HOPDONG HD ON TTHD.MAHD=HD.MAHD WHERE TTHD.MANHANVIEN IS NULL 
GO
-- lấy hợp đồng sắp hết hạn
ALTER PROC sp_LayHopDong_SapHetHan
@THANG int
AS
	SELECT * FROM THONGTIN_HOPDONG TTHD JOIN HOPDONG HD ON TTHD.MAHD=HD.MAHD WHERE TTHD.TGHH<DATEADD(MONTH,@THANG,GETDATE())

GO
