--INDEX TAI KHOAN--

CREATE INDEX idx_DANGNHAP ON TAIKHOAN (TENTK, MATKHAUTK,TINHTRANGTK) INCLUDE (MATK,NGAYTG)
GO
--INDEX KHACH HANG--
CREATE INDEX idx_MATK ON KHACHHANG (NGAYTG,MATK) INCLUDE (MAKH)
GO
--INDEX TAI XE
CREATE INDEX idx_MADIACHI ON TAIXE_CHITIET (MADIACHI)
GO
CREATE INDEX idx_MATK ON TAIXE (NGAYTG,MATK) INCLUDE (MATX)
GO
CREATE INDEX idx_MATKNGANHANG ON TAIXE_CHITIET (MATKNGANHANG)
GO
--INDEX DOI TAC--
CREATE INDEX idx_MATK ON DOITAC (MATK) INCLUDE (MADOITAC)
GO
CREATE INDEX idx_MATKNGANHANG ON DOITAC_CHITIET (MATKNGANHANG)
GO
CREATE INDEX idx_MADIACHI ON DOITAC_CHITIET (MADIACHI)
GO
--INDEX CHI NHANH--
CREATE INDEX idx_MATK ON CHINHANH (MATK) INCLUDE (MACN)
GO
CREATE INDEX idx_MATKNGANHANG ON CHINHANH (MATKNGANHANG)
GO
CREATE INDEX idx_MADT ON CHINHANH (MADT)
GO
--INDEX CUA HANG--
CREATE INDEX idx_TENCH ON CUAHANG (TENCH)
GO
CREATE INDEX idx_SLDH ON CUAHANG (SLDH)
GO
--INDEX THUC DON--
CREATE INDEX idx_TENMONAN ON THUCDON (TENMONAN)
GO
CREATE INDEX idx_GIA ON THUCDON (GIA)
GO
CREATE INDEX idx_SLDH ON THUCDON (SLDH)
GO
CREATE INDEX idx_MACN ON THUCDON (MACN)
GO
--INDEX NHAN VIEN--
CREATE INDEX idx_MATK ON NHANVIEN (MATK) INCLUDE (MANHANVIEN)
GO
CREATE INDEX idx_MADIACHI ON NHANVIEN_CHITIET (MADIACHI)
GO
--INDEX QUAN TRI VIEN
CREATE INDEX idx_MATK ON QUANTRIVIEN (MATK) INCLUDE (MAQTV)
GO
CREATE INDEX idx_MADIACHI ON QUANTRIVIEN (MADIACHI)
GO
--INDEX HOP DONG--
CREATE INDEX idx_MADT ON HOPDONG (MADOITAC)
GO
--INDEX THONG TIN HOP DONG--
CREATE INDEX idx_MANV ON THONGTIN_HOPDONG (MANHANVIEN)
GO
--INDEX HOPDONG CHI NHANH

CREATE INDEX idx_HD_HD ON HOPDONGCHINHANH (MAHD)
GO
--INDEX DON DAT HANG--
CREATE INDEX idx_MAKH ON DON_DH (MAKH) INCLUDE (PHIVANCHUYEN,PHISP)
GO
CREATE INDEX idx_MACN ON DON_DH (MACN) INCLUDE (PHISP,PTHH)
GO
CREATE INDEX idx_MADT ON DON_DH (MADT) INCLUDE (PHISP,PTHH)
GO
CREATE INDEX idx_MATX ON DON_DH (MATX) INCLUDE (PHIVANCHUYEN)
GO
CREATE INDEX idx_TDDH ON THUCDONDATHANG (MADH) INCLUDE (MAMONAN)
GO

CREATE INDEX idx_TDDHMA ON THUCDONDATHANG (MAMONAN) INCLUDE (SOLUONG,GIABAN)
GO

--INDEX DANH GIA CHI NHANH--
CREATE INDEX idx_MACN ON DANHGIA_CHINHANH (MACN) INCLUDE(RATING)
GO
CREATE INDEX idx_MADT ON DANHGIA_CHINHANH (MADT) INCLUDE (RATING)
GO
--INDEX DANH GIA MON AN--
CREATE INDEX idx_MAMONAN ON DANHGIA_MONAN (MAMONAN) INCLUDE (RATING)
GO
--INDEX DANH GIA TAI XE--
CREATE INDEX idx_MATX ON DANHGIA_TX (MATX)	INCLUDE(RATING)
GO
--INDEX PHUONG--
CREATE INDEX idx_MAHUYEN ON PHUONG (MAHUYEN)
Go
--INDEX DIA CHI--
CREATE INDEX idx_MAPHUONG ON DIACHI (MAPHUONG)
GO
