--INDEX TAI KHOAN--

DROP INDEX idx_DANGNHAP ON TAIKHOAN 
GO
--INDEX KHACH HANG--
DROP INDEX idx_MATK ON KHACHHANG 
GO
--INDEX TAI XE
DROP INDEX idx_MADIACHI ON TAIXE_CHITIET 
GO
DROP INDEX idx_MATK ON TAIXE 
GO
DROP INDEX idx_MATKNGANHANG ON TAIXE_CHITIET 
GO
--INDEX DOI TAC--
DROP INDEX idx_MATK ON DOITAC 
GO
DROP INDEX idx_MATKNGANHANG ON DOITAC_CHITIET 
GO
DROP INDEX idx_MADIACHI ON DOITAC_CHITIET 
GO
--INDEX CHI NHANH--
DROP INDEX idx_MATK ON CHINHANH 
GO
DROP INDEX idx_MATKNGANHANG ON CHINHANH 
GO
DROP INDEX idx_MADT ON CHINHANH 
GO
--INDEX CUA HANG--
DROP INDEX idx_TENCH ON CUAHANG 
GO
DROP INDEX idx_SLDH ON CUAHANG 
GO
--INDEX THUC DON--
DROP INDEX idx_TENMONAN ON THUCDON 
GO
DROP INDEX idx_GIA ON THUCDON 
GO
DROP INDEX idx_SLDH ON THUCDON 
GO
DROP INDEX idx_MACN ON THUCDON 
GO
--INDEX NHAN VIEN--
DROP INDEX idx_MATK ON NHANVIEN 
GO
DROP INDEX idx_MADIACHI ON NHANVIEN_CHITIET 
GO
--INDEX QUAN TRI VIEN
DROP INDEX idx_MATK ON QUANTRIVIEN 
GO
DROP INDEX idx_MADIACHI ON QUANTRIVIEN 
GO
--INDEX HOP DONG--
DROP INDEX idx_MADT ON HOPDONG 
GO
--INDEX THONG TIN HOP DONG--
DROP INDEX idx_MANV ON THONGTIN_HOPDONG 
GO
--INDEX HOPDONG CHI NHANH

DROP INDEX idx_HD_HD ON HOPDONGCHINHANH 
GO
--INDEX DON DAT HANG--
DROP INDEX idx_MAKH ON DON_DH 
GO
DROP INDEX idx_MACN ON DON_DH 
GO
DROP INDEX idx_MADT ON DON_DH 
GO
DROP INDEX idx_MATX ON DON_DH 
GO
DROP INDEX idx_TDDH ON THUCDONDATHANG 
GO

DROP INDEX idx_TDDHMA ON THUCDONDATHANG 
GO

--INDEX DANH GIA CHI NHANH--
DROP INDEX idx_MACN ON DANHGIA_CHINHANH 
GO
DROP INDEX idx_MADT ON DANHGIA_CHINHANH 
GO
--INDEX DANH GIA MON AN--
DROP INDEX idx_MAMONAN ON DANHGIA_MONAN 
GO
--INDEX DANH GIA TAI XE--
DROP INDEX idx_MATX ON DANHGIA_TX 
GO
--INDEX PHUONG--
DROP INDEX idx_MAHUYEN ON PHUONG 
Go
--INDEX DIA CHI--
DROP INDEX idx_MAPHUONG ON DIACHI 
GO
