USE QL_BANHANG_TRANHCHAP
GO
ALTER
 PROC sp_HopDong_YeuCauGiaHan
@MADT VARCHAR(10),
@MAHD VARCHAR(10),
@THOIHAN INT
AS
BEGIN TRAN
IF NOT EXISTS (SELECT MADOITAC FROM DOITAC WHERE MADOITAC=@MADT)
BEGIN
	ROLLBACK TRAN
	RAISERROR ('KHONG TON TAI DOI TAC ',16,1)
	RETURN
END
IF NOT EXISTS (SELECT MAHD FROM HOPDONG WHERE MAHD=@MAHD)
BEGIN
	ROLLBACK TRAN
	RAISERROR ('KHONG TON TAI HOP DONG ',16,1)
	RETURN
END
DECLARE @MAHH VARCHAR(10)
IF EXISTS (SELECT * FROM HOPDONG HD JOIN THONGTIN_HOPDONG  TTHD  ON TTHD.MAHD=HD.MAHD WHERE HD.MAHD=@MAHD AND HD.MADOITAC=@MADT AND TTHD.MANHANVIEN IS NULL)
BEGIN
	IF NOT EXISTS(SELECT COUNT (MAHH) FROM THONGTIN_HOAHONG WHERE GETDATE() BETWEEN NGAYBD AND NGAYHH HAVING COUNT (MAHH)=1)
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('LAY THONG TIN HOA HONG THAT BAI ',16,1)
		RETURN
	END
	SET @MAHH = (SELECT MAHH FROM THONGTIN_HOAHONG WHERE GETDATE() BETWEEN NGAYBD AND NGAYHH)
	UPDATE THONGTIN_HOPDONG SET THOIHAN=@THOIHAN,MAHH=@MAHH WHERE MAHD=@MAHD AND MANHANVIEN IS NULL
	IF @@ERROR <>0
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('YEU CAU GIA HAN THAT BAI ',16,1)
		RETURN
	END
END
ELSE
BEGIN
	WAITFOR DELAY '0:00:10'
	DECLARE @STT INT = (SELECT MAX(STT) FROM THONGTIN_HOPDONG WHERE MAHD=@MAHD) 
	IF @STT>0
	SET @STT =@STT +1
	ELSE
	SET @STT=1
	IF NOT EXISTS(SELECT COUNT (MAHH) FROM THONGTIN_HOAHONG  WHERE GETDATE() BETWEEN NGAYBD AND NGAYHH HAVING COUNT (MAHH)=1)
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('LAY THONG TIN HOA HONG THAT BAI ',16,1)
		RETURN
	END
	SET @MAHH= (SELECT MAHH FROM THONGTIN_HOAHONG WHERE GETDATE() BETWEEN NGAYBD AND NGAYHH)
	EXEC sp_ThemThongTinHopDong @MAHD,@STT,@THOIHAN,NULL,NULL,@MAHH,NULL
	IF @@ERROR <>0
	BEGIN
		ROLLBACK TRAN
		RAISERROR ('YEU CAU GIA HAN THAT BAI ',16,1)
		RETURN
	END
END
COMMIT TRAN
GO
USE master